server:
    port: 9001 # 分别 9000 9001 9002
spring:
    application:
        name: eureka-consumer-ribbon
eureka:
    client:
        service-url:
            defaultZone: http://localhost:7000/eureka/
