spring:
  application:
#    name: eureka-consumer-feign
    name: eureka-consumer-hystrix
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka/
server:
  port: 9003 # 分别 9000 9001 9002
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream